server:
  port: 8080

grpc:
  server:
    port: 9090
    security:
      enabled: true
      certificateChain: classpath:certs/server.crt
      privateKey: classpath:certs/server.key

spring:
  application:
    name: grpcserver